# Generated by Django 4.2 on 2024-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
