# Generated by Django 4.2 on 2024-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_service",
            "0002_remove_customer_phone_number_customer_address_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicerequest",
            old_name="created_at",
            new_name="submitted_at",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
